// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUvRye-GuLjr86X_dAJQ-zQBGsmm3EkSg',
    appId: '1:146799845621:web:eca5e3dbad0cb60ea7e5bc',
    messagingSenderId: '146799845621',
    projectId: 'amst-flutter-db-934f7',
    authDomain: 'amst-flutter-db-934f7.firebaseapp.com',
    databaseURL: 'https://amst-flutter-db-934f7-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-934f7.appspot.com',
    measurementId: 'G-EB5VV7KLSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTRcyadidw-d7qWS0WEddlObxWEDh4prc',
    appId: '1:146799845621:android:3094d27efaab21d0a7e5bc',
    messagingSenderId: '146799845621',
    projectId: 'amst-flutter-db-934f7',
    databaseURL: 'https://amst-flutter-db-934f7-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-934f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZC4RCcjZ4MsYbRvIMPwqLgXfVMsDURZ4',
    appId: '1:146799845621:ios:e9b985265fc98a04a7e5bc',
    messagingSenderId: '146799845621',
    projectId: 'amst-flutter-db-934f7',
    databaseURL: 'https://amst-flutter-db-934f7-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-934f7.appspot.com',
    iosClientId: '146799845621-pvdcbor38h31mqge7bvcq85pu02l6hmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFlutterDb04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZC4RCcjZ4MsYbRvIMPwqLgXfVMsDURZ4',
    appId: '1:146799845621:ios:755f03965f546654a7e5bc',
    messagingSenderId: '146799845621',
    projectId: 'amst-flutter-db-934f7',
    databaseURL: 'https://amst-flutter-db-934f7-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-934f7.appspot.com',
    iosClientId: '146799845621-k0b9kve9tt695bm2a90o5v0oqmecdp5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFlutterDb04.RunnerTests',
  );
}
